const swaggerJSDoc = require('swagger-jsdoc');
const fs = require('fs');
const path = require('path');

// Try to load auto-generated swagger documentation
let autoGeneratedSpecs = {};
const autoGenPath = path.join(__dirname, '../docs/swagger-output.json');

if (fs.existsSync(autoGenPath)) {
  try {
    autoGeneratedSpecs = require(autoGenPath);
    console.log('✅ Auto-generated Swagger documentation loaded');
  } catch (error) {
    console.log('⚠️  Could not load auto-generated docs, using JSDoc only');
  }
} else {
  console.log('ℹ️  Auto-generated docs not found. Run "npm run swagger:generate" to create them.');
}

// Manual JSDoc configuration (your existing setup)
const jsDocOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'FileVault API',
      version: '1.0.0',
      description: `
# 🔐 FileVault - Secure Cloud File Storage API

## Overview
FileVault is an enterprise-grade secure file storage solution with advanced authentication and AWS S3 integration.

## Features
- 🔒 JWT-based authentication with email verification
- 📁 Secure file upload/download with AWS S3
- 🛡️ Rate limiting and security middleware
- 📊 Comprehensive logging and monitoring
- 🔗 Shareable links with expiration controls

## Authentication
Most endpoints require a Bearer token in the Authorization header:
\`\`\`
Authorization: Bearer <your-jwt-token>
\`\`\`

## Rate Limits
- Auth endpoints: 10 requests per 15 minutes
- File operations: 100 requests per 15 minutes
- Anonymous uploads: 5 requests per minute

## File Upload Constraints
- Maximum file size: 5GB
- Supported formats: Images, Documents, Archives, Media
- File type validation enforced
      `,
      contact: {
        name: 'Hariom Virkhare',
        email: 'hariomvirkhare02@gmail.com',
        url: 'https://github.com/hariomop12'
      },
      license: {
        name: 'ISC',
        url: 'https://opensource.org/licenses/ISC'
      }
    },
    servers: [
      {
        url: 'http://localhost:3000',
        description: 'Development server'
      },
      {
        url: 'https://api.filevault.com',
        description: 'Production server'
      }
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      },
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: {
              type: 'integer',
              description: 'User ID'
            },
            name: {
              type: 'string',
              description: 'User full name'
            },
            email: {
              type: 'string',
              format: 'email',
              description: 'User email address'
            },
            email_verified: {
              type: 'boolean',
              description: 'Email verification status'
            },
            storage_quota: {
              type: 'integer',
              description: 'Storage quota in bytes'
            },
            created_at: {
              type: 'string',
              format: 'date-time',
              description: 'Account creation timestamp'
            }
          }
        },
        File: {
          type: 'object',
          properties: {
            id: {
              type: 'integer',
              description: 'File ID'
            },
            filename: {
              type: 'string',
              description: 'Original filename'
            },
            file_path: {
              type: 'string',
              description: 'File storage path'
            },
            file_size: {
              type: 'integer',
              description: 'File size in bytes'
            },
            mime_type: {
              type: 'string',
              description: 'File MIME type'
            },
            uploaded_at: {
              type: 'string',
              format: 'date-time',
              description: 'Upload timestamp'
            },
            user_id: {
              type: 'integer',
              description: 'Owner user ID (null for anonymous)'
            }
          }
        },
        ApiResponse: {
          type: 'object',
          properties: {
            success: {
              type: 'boolean',
              example: true
            },
            message: {
              type: 'string',
              description: 'Success message'
            },
            data: {
              type: 'object',
              description: 'Response data'
            }
          }
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            success: {
              type: 'boolean',
              example: false
            },
            message: {
              type: 'string',
              description: 'Error message'
            },
            error: {
              type: 'string',
              description: 'Error details'
            }
          }
        }
      }
    },
    tags: [
      {
        name: 'Authentication',
        description: 'User authentication and account management'
      },
      {
        name: 'Anonymous Files',
        description: 'File operations without authentication'
      },
      {
        name: 'User Files',
        description: 'Authenticated user file management'
      },
      {
        name: 'Health',
        description: 'API health and status endpoints'
      }
    ]
  },
  apis: [
    './routes/*.js',
    './controllers/*.js',
    './app.js'
  ]
};

// Generate JSDoc specs
const jsDocSpecs = swaggerJSDoc(jsDocOptions);

// Merge auto-generated specs with JSDoc specs if available
const mergeSpecs = (jsDoc, autoGen) => {
  if (!autoGen || !autoGen.paths) {
    return jsDoc;
  }

  // Start with JSDoc as base
  const merged = { ...jsDoc };

  // Merge paths from auto-generated specs
  merged.paths = {
    ...merged.paths,
    ...autoGen.paths
  };

  // Merge definitions/components if they exist
  if (autoGen.definitions) {
    merged.components = merged.components || {};
    merged.components.schemas = {
      ...merged.components.schemas,
      ...autoGen.definitions
    };
  }

  return merged;
};

const specs = mergeSpecs(jsDocSpecs, autoGeneratedSpecs);

module.exports = specs;